# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Coffchat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coffchat
  pod 'Alamofire', '~> 5.0'     # http
  pod 'CocoaAsyncSocket'        # socket
  #pod 'Socket.IO-Client-Swift', '~> 15.2.0' # socket
  pod 'SwiftProtobuf', '~> 1.0' # protobuf
  pod 'SnapKit', '~> 5.0.0' # 自动布局第三方库
  
end
