# fixed: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_b_e_4.txt, error: execution expired
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Coffchat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coffchat
  pod 'Alamofire', '~> 5.2'     # http
  pod 'CocoaAsyncSocket', '~> 7.6.3'        # socket
  #pod 'Socket.IO-Client-Swift', '~> 15.2.0' # socket
  pod 'SwiftProtobuf', '~> 1.0' # protobuf
  pod 'SnapKit', '~> 5.0.0'  # 自动布局第三方库
  pod 'SwiftyJSON', '~> 4.0' # json解析库
  pod 'Dollar', '9.0.0'      # 操作数组的神器，比如将数组划分成若干个子集
  pod 'RxSwift', '~> 5'      # 一个组合异步和事件驱动编程的库
  pod 'RxCocoa', '~> 5'      # iOS响应式编程中的两个主流框架（RxSwift+RxCocoa）
  pod 'BEMCheckBox'          # 高雅的iOS复选框
  pod 'Chrysan'              # 菊花组件
  pod 'CryptoSwift'          # hash(md5,sha256),crc32 , 1.3.8
end
