1.sip呼叫流程
@startuml
Alice -> Bob: INVITE
Bob --> Alice: 100 Trying
Bob --> Alice: 180 Ringing
Bob --> Alice: 200 OK
Alice -> Bob: ACK

Alice -> Bob: RTP
Bob -> Alice:
Bob -> Alice: RTP
Alice -> Bob:

Bob -> Alice: BYE
Alice -> Bob: 200 OK
@enduml

2.微信
@startuml

state alice{
  [*] --> 拨号中
  拨号中 --> 已接通1: 2.收到100 Trying
  拨号中 --> bob: 1.发送Invite
  已接通1 --> 等待对方接听: 5.收到180 Ringing
  等待对方接听 --> 取消1
  通话中1 --> 挂断1
  挂断1 --> 结束1
  取消1 --> 结束1
  结束1 --> message
}

state bob{
  [*] --> 连接中: 3.收到Invite
  连接中 -> 已接通
  已接通 -> 持续振铃: 4.回复180 Ringing
  持续振铃 --> 接听: 6.发送200 OK
  持续振铃 --> 取消2
  接听 --> 通话中
  接听 --> 通话中1: 7.收到200 OK
  通话中 --> 挂断: 8.发送Bye
  挂断 --> 结束
  挂断 --> 结束1: 9.收到Bye
  取消2 --> 结束
  结束 --> message
}

state message{
  [*] --> 通话时长01分00秒
  [*] --> 对方已取消
  [*] --> 已取消
}
@enduml

3.声网SDK流程
@startuml
alice -> agora: 0. ....
alice -> im: 1.invite(pb)
im -> alice: 2.100 Trying(pb)
im -> bob: 3.invite(pb)
bob -> im: 4.180 Ringing(pb)
im -> alice: 5.180 Ringing(pb)
bob -> agora: 6.joinChannel
agora -> bob: 7.onJoinChannelSuccess
bob -> im: 8.200 ok(pb)
im -> bob: 9.ack(pb)
im -> alice: 10.200 ok(pb)
alice -> im: 11.ack(pb)

alice -> agora: 13.joinChannel
agora -> alice: 14.onJoinChannelSuccess
agora -> bob: 15.onUserJoined

alice <-> bob: 15.Agora voice/video data stream
alice <-> bob: 16.Agora voice/video data stream
bob -> im: 17.heartbeat(pb)
alice -> im: 18.heartbeat(pb)
alice <-> bob: 19.Agora voice/video data stream
bob -> agora: 20.levelChannel
agora -> alice: 21.onUserOffline,reason=1
alice -> agora: 22.levelChannel
agora -> agora: 23.delete Channel
bob -> im: 24.BYE(pb)
im -> bob: 25.200 OK(pb)
im -> alice: 26.msg,type=tips,content=通话时长01分00秒(pb)
alice -> im: 27.ack
im -> bob: 28.msg(pb)
bob -> im: 29.ack
@enduml

4.SIP和声网结合
@startuml
Alice -> IM: INVITE
IM -> Bob: INVITE
IM --> Alice: 100 Trying
Bob --> IM: 180 Ringing
IM --> Alice: 180 Ringing
Bob --> IM: 200 OK
IM -> Alice: 200 OK
Alice -> IM: ACK
IM -> Bob: ACK

Alice <-> Bob: Agora SDK voice/video data
Alice <-> Bob: ……
Alice <-> Bob: Agora SDK voice/video data

Bob -> IM: BYE
IM -> Alice: BYE
Alice -> IM: 200 OK
IM -> Bob: 200 OK
@enduml