// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CIM.Def.proto

package cim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 外部消息：客户端 <-> 服务器消息定义
type CIMCmdID int32

const (
	CIMCmdID_kCIM_CID_UNKNOWN                         CIMCmdID = 0
	CIMCmdID_kCIM_CID_LOGIN_AUTH_TOKEN_REQ            CIMCmdID = 257
	CIMCmdID_kCIM_CID_LOGIN_AUTH_TOKEN_RSP            CIMCmdID = 258
	CIMCmdID_kCIM_CID_LOGIN_AUTH_LOGOUT_REQ           CIMCmdID = 259
	CIMCmdID_kCIM_CID_LOGIN_AUTH_LOGOUT_RSP           CIMCmdID = 260
	CIMCmdID_kCIM_CID_LOGIN_HEARTBEAT                 CIMCmdID = 261
	CIMCmdID_kCIM_CID_LIST_RECENT_CONTACT_SESSION_REQ CIMCmdID = 513
	CIMCmdID_kCIM_CID_LIST_RECENT_CONTACT_SESSION_RSP CIMCmdID = 514
	// kCIM_CID_LIST_UNREAD_CNT_REQ = 0x0203; // 未读消息计数列表请求
	// kCIM_CID_LIST_UNREAD_CNT_RSP = 0x0204;
	CIMCmdID_kCIM_CID_LIST_MSG_REQ              CIMCmdID = 517
	CIMCmdID_kCIM_CID_LIST_MSG_RSP              CIMCmdID = 518
	CIMCmdID_kCIM_CID_MSG_DATA                  CIMCmdID = 769
	CIMCmdID_kCIM_CID_MSG_DATA_ACK              CIMCmdID = 770
	CIMCmdID_kCIM_CID_MSG_READ_ACK              CIMCmdID = 771
	CIMCmdID_kCIM_CID_MSG_READ_NOTIFY           CIMCmdID = 772
	CIMCmdID_kCIM_CID_MSG_GET_LATEST_MSG_ID_REQ CIMCmdID = 773
	CIMCmdID_kCIM_CID_MSG_GET_LATEST_MSG_ID_RSP CIMCmdID = 774
	CIMCmdID_kCIM_CID_MSG_GET_BY_MSG_ID_REQ     CIMCmdID = 775
	CIMCmdID_kCIM_CID_MSG_GET_BY_MSG_ID_RSP     CIMCmdID = 776
	CIMCmdID_kCIM_CID_VOIP_INVITE_REQ           CIMCmdID = 1025
	CIMCmdID_kCIM_CID_VOIP_INVITE_REPLY         CIMCmdID = 1026
	CIMCmdID_kCIM_CID_VOIP_INVITE_REPLY_ACK     CIMCmdID = 1027
	CIMCmdID_kCIM_CID_VOIP_HEARTBEAT            CIMCmdID = 1028
	CIMCmdID_kCIM_CID_VOIP_BYE_REQ              CIMCmdID = 1029
	CIMCmdID_kCIM_CID_VOIP_BYE_RSP              CIMCmdID = 1030
	CIMCmdID_kCIM_CID_VOIP_BYE_NOTIFY           CIMCmdID = 1031
)

var CIMCmdID_name = map[int32]string{
	0:    "kCIM_CID_UNKNOWN",
	257:  "kCIM_CID_LOGIN_AUTH_TOKEN_REQ",
	258:  "kCIM_CID_LOGIN_AUTH_TOKEN_RSP",
	259:  "kCIM_CID_LOGIN_AUTH_LOGOUT_REQ",
	260:  "kCIM_CID_LOGIN_AUTH_LOGOUT_RSP",
	261:  "kCIM_CID_LOGIN_HEARTBEAT",
	513:  "kCIM_CID_LIST_RECENT_CONTACT_SESSION_REQ",
	514:  "kCIM_CID_LIST_RECENT_CONTACT_SESSION_RSP",
	517:  "kCIM_CID_LIST_MSG_REQ",
	518:  "kCIM_CID_LIST_MSG_RSP",
	769:  "kCIM_CID_MSG_DATA",
	770:  "kCIM_CID_MSG_DATA_ACK",
	771:  "kCIM_CID_MSG_READ_ACK",
	772:  "kCIM_CID_MSG_READ_NOTIFY",
	773:  "kCIM_CID_MSG_GET_LATEST_MSG_ID_REQ",
	774:  "kCIM_CID_MSG_GET_LATEST_MSG_ID_RSP",
	775:  "kCIM_CID_MSG_GET_BY_MSG_ID_REQ",
	776:  "kCIM_CID_MSG_GET_BY_MSG_ID_RSP",
	1025: "kCIM_CID_VOIP_INVITE_REQ",
	1026: "kCIM_CID_VOIP_INVITE_REPLY",
	1027: "kCIM_CID_VOIP_INVITE_REPLY_ACK",
	1028: "kCIM_CID_VOIP_HEARTBEAT",
	1029: "kCIM_CID_VOIP_BYE_REQ",
	1030: "kCIM_CID_VOIP_BYE_RSP",
	1031: "kCIM_CID_VOIP_BYE_NOTIFY",
}

var CIMCmdID_value = map[string]int32{
	"kCIM_CID_UNKNOWN":                         0,
	"kCIM_CID_LOGIN_AUTH_TOKEN_REQ":            257,
	"kCIM_CID_LOGIN_AUTH_TOKEN_RSP":            258,
	"kCIM_CID_LOGIN_AUTH_LOGOUT_REQ":           259,
	"kCIM_CID_LOGIN_AUTH_LOGOUT_RSP":           260,
	"kCIM_CID_LOGIN_HEARTBEAT":                 261,
	"kCIM_CID_LIST_RECENT_CONTACT_SESSION_REQ": 513,
	"kCIM_CID_LIST_RECENT_CONTACT_SESSION_RSP": 514,
	"kCIM_CID_LIST_MSG_REQ":                    517,
	"kCIM_CID_LIST_MSG_RSP":                    518,
	"kCIM_CID_MSG_DATA":                        769,
	"kCIM_CID_MSG_DATA_ACK":                    770,
	"kCIM_CID_MSG_READ_ACK":                    771,
	"kCIM_CID_MSG_READ_NOTIFY":                 772,
	"kCIM_CID_MSG_GET_LATEST_MSG_ID_REQ":       773,
	"kCIM_CID_MSG_GET_LATEST_MSG_ID_RSP":       774,
	"kCIM_CID_MSG_GET_BY_MSG_ID_REQ":           775,
	"kCIM_CID_MSG_GET_BY_MSG_ID_RSP":           776,
	"kCIM_CID_VOIP_INVITE_REQ":                 1025,
	"kCIM_CID_VOIP_INVITE_REPLY":               1026,
	"kCIM_CID_VOIP_INVITE_REPLY_ACK":           1027,
	"kCIM_CID_VOIP_HEARTBEAT":                  1028,
	"kCIM_CID_VOIP_BYE_REQ":                    1029,
	"kCIM_CID_VOIP_BYE_RSP":                    1030,
	"kCIM_CID_VOIP_BYE_NOTIFY":                 1031,
}

func (x CIMCmdID) String() string {
	return proto.EnumName(CIMCmdID_name, int32(x))
}

func (CIMCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{0}
}

// 内部消息：服务器 <-> 服务器消息定义
type CIMIntenralCmdID int32

const (
	CIMIntenralCmdID_kCIM_SID_UNKNOWN         CIMIntenralCmdID = 0
	CIMIntenralCmdID_kCIM_SID_DB_VALIDATE_REQ CIMIntenralCmdID = 1793
	CIMIntenralCmdID_kCIM_SID_DB_VALIDATE_RSP CIMIntenralCmdID = 1794
)

var CIMIntenralCmdID_name = map[int32]string{
	0:    "kCIM_SID_UNKNOWN",
	1793: "kCIM_SID_DB_VALIDATE_REQ",
	1794: "kCIM_SID_DB_VALIDATE_RSP",
}

var CIMIntenralCmdID_value = map[string]int32{
	"kCIM_SID_UNKNOWN":         0,
	"kCIM_SID_DB_VALIDATE_REQ": 1793,
	"kCIM_SID_DB_VALIDATE_RSP": 1794,
}

func (x CIMIntenralCmdID) String() string {
	return proto.EnumName(CIMIntenralCmdID_name, int32(x))
}

func (CIMIntenralCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{1}
}

type CIMErrorCode int32

const (
	// 通用错误码
	CIMErrorCode_kCIM_ERR_SUCCSSE        CIMErrorCode = 0
	CIMErrorCode_kCIM_ERR_INTERNAL_ERROR CIMErrorCode = 1
	// 账号错误码
	CIMErrorCode_kCIM_ERR_LOGIN_DB_VALIDATE_FAILED CIMErrorCode = 200
	CIMErrorCode_kCIM_ERR_LOGIN_VERSION_TOO_OLD    CIMErrorCode = 201
	CIMErrorCode_kCIM_ERR_LOGIN_INVALID_USER_TOKEN CIMErrorCode = 202
	// HTTP API 错码
	CIMErrorCode_kCIM_ERROR_USER_ALREADY_EXIST     CIMErrorCode = 900
	CIMErrorCode_kCIM_ERROR_USER_INVALID_PARAMETER CIMErrorCode = 901
	CIMErrorCode_kCIM_ERROR_USER_NOT_EXIST         CIMErrorCode = 902
)

var CIMErrorCode_name = map[int32]string{
	0:   "kCIM_ERR_SUCCSSE",
	1:   "kCIM_ERR_INTERNAL_ERROR",
	200: "kCIM_ERR_LOGIN_DB_VALIDATE_FAILED",
	201: "kCIM_ERR_LOGIN_VERSION_TOO_OLD",
	202: "kCIM_ERR_LOGIN_INVALID_USER_TOKEN",
	900: "kCIM_ERROR_USER_ALREADY_EXIST",
	901: "kCIM_ERROR_USER_INVALID_PARAMETER",
	902: "kCIM_ERROR_USER_NOT_EXIST",
}

var CIMErrorCode_value = map[string]int32{
	"kCIM_ERR_SUCCSSE":                  0,
	"kCIM_ERR_INTERNAL_ERROR":           1,
	"kCIM_ERR_LOGIN_DB_VALIDATE_FAILED": 200,
	"kCIM_ERR_LOGIN_VERSION_TOO_OLD":    201,
	"kCIM_ERR_LOGIN_INVALID_USER_TOKEN": 202,
	"kCIM_ERROR_USER_ALREADY_EXIST":     900,
	"kCIM_ERROR_USER_INVALID_PARAMETER": 901,
	"kCIM_ERROR_USER_NOT_EXIST":         902,
}

func (x CIMErrorCode) String() string {
	return proto.EnumName(CIMErrorCode_name, int32(x))
}

func (CIMErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{2}
}

// 客户端类型
type CIMClientType int32

const (
	CIMClientType_kCIM_CLIENT_TYPE_DEFAULT CIMClientType = 0
	CIMClientType_kCIM_CLIENT_TYPE_ANDROID CIMClientType = 1
	CIMClientType_kCIM_CLIENT_TYPE_IOS     CIMClientType = 2
	CIMClientType_kCIM_CLIENT_TYPE_WEB     CIMClientType = 3
)

var CIMClientType_name = map[int32]string{
	0: "kCIM_CLIENT_TYPE_DEFAULT",
	1: "kCIM_CLIENT_TYPE_ANDROID",
	2: "kCIM_CLIENT_TYPE_IOS",
	3: "kCIM_CLIENT_TYPE_WEB",
}

var CIMClientType_value = map[string]int32{
	"kCIM_CLIENT_TYPE_DEFAULT": 0,
	"kCIM_CLIENT_TYPE_ANDROID": 1,
	"kCIM_CLIENT_TYPE_IOS":     2,
	"kCIM_CLIENT_TYPE_WEB":     3,
}

func (x CIMClientType) String() string {
	return proto.EnumName(CIMClientType_name, int32(x))
}

func (CIMClientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{3}
}

// 会话类型
type CIMSessionType int32

const (
	CIMSessionType_kCIM_SESSION_TYPE_Invalid CIMSessionType = 0
	CIMSessionType_kCIM_SESSION_TYPE_SINGLE  CIMSessionType = 1
	CIMSessionType_kCIM_SESSION_TYPE_GROUP   CIMSessionType = 2
)

var CIMSessionType_name = map[int32]string{
	0: "kCIM_SESSION_TYPE_Invalid",
	1: "kCIM_SESSION_TYPE_SINGLE",
	2: "kCIM_SESSION_TYPE_GROUP",
}

var CIMSessionType_value = map[string]int32{
	"kCIM_SESSION_TYPE_Invalid": 0,
	"kCIM_SESSION_TYPE_SINGLE":  1,
	"kCIM_SESSION_TYPE_GROUP":   2,
}

func (x CIMSessionType) String() string {
	return proto.EnumName(CIMSessionType_name, int32(x))
}

func (CIMSessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{4}
}

// 消息类型
type CIMMsgType int32

const (
	CIMMsgType_kCIM_MSG_TYPE_UNKNOWN      CIMMsgType = 0
	CIMMsgType_kCIM_MSG_TYPE_TEXT         CIMMsgType = 1
	CIMMsgType_kCIM_MSG_TYPE_FILE         CIMMsgType = 2
	CIMMsgType_kCIM_MSG_TYPE_IMAGE        CIMMsgType = 3
	CIMMsgType_kCIM_MSG_TYPE_AUDIO        CIMMsgType = 4
	CIMMsgType_kCIM_MSG_TYPE_VIDEO        CIMMsgType = 5
	CIMMsgType_kCIM_MSG_TYPE_LOCATION     CIMMsgType = 6
	CIMMsgType_kCIM_MSG_TYPE_ROBOT        CIMMsgType = 7
	CIMMsgType_kCIM_MSG_TYPE_TIPS         CIMMsgType = 8
	CIMMsgType_kCIM_MSG_TYPE_NOTIFACATION CIMMsgType = 9
)

var CIMMsgType_name = map[int32]string{
	0: "kCIM_MSG_TYPE_UNKNOWN",
	1: "kCIM_MSG_TYPE_TEXT",
	2: "kCIM_MSG_TYPE_FILE",
	3: "kCIM_MSG_TYPE_IMAGE",
	4: "kCIM_MSG_TYPE_AUDIO",
	5: "kCIM_MSG_TYPE_VIDEO",
	6: "kCIM_MSG_TYPE_LOCATION",
	7: "kCIM_MSG_TYPE_ROBOT",
	8: "kCIM_MSG_TYPE_TIPS",
	9: "kCIM_MSG_TYPE_NOTIFACATION",
}

var CIMMsgType_value = map[string]int32{
	"kCIM_MSG_TYPE_UNKNOWN":      0,
	"kCIM_MSG_TYPE_TEXT":         1,
	"kCIM_MSG_TYPE_FILE":         2,
	"kCIM_MSG_TYPE_IMAGE":        3,
	"kCIM_MSG_TYPE_AUDIO":        4,
	"kCIM_MSG_TYPE_VIDEO":        5,
	"kCIM_MSG_TYPE_LOCATION":     6,
	"kCIM_MSG_TYPE_ROBOT":        7,
	"kCIM_MSG_TYPE_TIPS":         8,
	"kCIM_MSG_TYPE_NOTIFACATION": 9,
}

func (x CIMMsgType) String() string {
	return proto.EnumName(CIMMsgType_name, int32(x))
}

func (CIMMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{5}
}

// 消息状态
type CIMMsgStatus int32

const (
	CIMMsgStatus_kCIM_MSG_STATUS_NONE      CIMMsgStatus = 0
	CIMMsgStatus_kCIM_MSG_STATUS_UNREAD    CIMMsgStatus = 1
	CIMMsgStatus_kCIM_MSG_STATUS_READ      CIMMsgStatus = 2
	CIMMsgStatus_kCIM_MSG_STATUS_DELETED   CIMMsgStatus = 3
	CIMMsgStatus_kCIM_MSG_STATUS_SENDING   CIMMsgStatus = 4
	CIMMsgStatus_kCIM_MSG_STATUS_SENT      CIMMsgStatus = 5
	CIMMsgStatus_kCIM_MSG_STATUS_RECEIPT   CIMMsgStatus = 6
	CIMMsgStatus_kCIM_MSG_STATUS_DRAFT     CIMMsgStatus = 7
	CIMMsgStatus_kCIM_MSG_STATUS_SendCacel CIMMsgStatus = 8
	CIMMsgStatus_kCIM_MSG_STATUS_REFUSED   CIMMsgStatus = 9
	CIMMsgStatus_kCIM_MSG_STATUS_FAILED    CIMMsgStatus = 10
)

var CIMMsgStatus_name = map[int32]string{
	0:  "kCIM_MSG_STATUS_NONE",
	1:  "kCIM_MSG_STATUS_UNREAD",
	2:  "kCIM_MSG_STATUS_READ",
	3:  "kCIM_MSG_STATUS_DELETED",
	4:  "kCIM_MSG_STATUS_SENDING",
	5:  "kCIM_MSG_STATUS_SENT",
	6:  "kCIM_MSG_STATUS_RECEIPT",
	7:  "kCIM_MSG_STATUS_DRAFT",
	8:  "kCIM_MSG_STATUS_SendCacel",
	9:  "kCIM_MSG_STATUS_REFUSED",
	10: "kCIM_MSG_STATUS_FAILED",
}

var CIMMsgStatus_value = map[string]int32{
	"kCIM_MSG_STATUS_NONE":      0,
	"kCIM_MSG_STATUS_UNREAD":    1,
	"kCIM_MSG_STATUS_READ":      2,
	"kCIM_MSG_STATUS_DELETED":   3,
	"kCIM_MSG_STATUS_SENDING":   4,
	"kCIM_MSG_STATUS_SENT":      5,
	"kCIM_MSG_STATUS_RECEIPT":   6,
	"kCIM_MSG_STATUS_DRAFT":     7,
	"kCIM_MSG_STATUS_SendCacel": 8,
	"kCIM_MSG_STATUS_REFUSED":   9,
	"kCIM_MSG_STATUS_FAILED":    10,
}

func (x CIMMsgStatus) String() string {
	return proto.EnumName(CIMMsgStatus_name, int32(x))
}

func (CIMMsgStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{6}
}

// 会话状态
type CIMSessionStatusType int32

const (
	CIMSessionStatusType_kCIM_SESSION_STATUS_OK     CIMSessionStatusType = 0
	CIMSessionStatusType_kCIM_SESSION_STATUS_DELETE CIMSessionStatusType = 1
)

var CIMSessionStatusType_name = map[int32]string{
	0: "kCIM_SESSION_STATUS_OK",
	1: "kCIM_SESSION_STATUS_DELETE",
}

var CIMSessionStatusType_value = map[string]int32{
	"kCIM_SESSION_STATUS_OK":     0,
	"kCIM_SESSION_STATUS_DELETE": 1,
}

func (x CIMSessionStatusType) String() string {
	return proto.EnumName(CIMSessionStatusType_name, int32(x))
}

func (CIMSessionStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{7}
}

// 消息属性
type CIMMsgFeature int32

const (
	CIMMsgFeature_kCIM_MSG_FEATURE_DEFAULT CIMMsgFeature = 0
	// kCIM_MSG_FEATURE_LEAVE_MSG = 1;      // 离线消息(和漫游消息有何区别)
	CIMMsgFeature_kCIM_MSG_FEATURE_ROAM_MSG CIMMsgFeature = 2
)

var CIMMsgFeature_name = map[int32]string{
	0: "kCIM_MSG_FEATURE_DEFAULT",
	2: "kCIM_MSG_FEATURE_ROAM_MSG",
}

var CIMMsgFeature_value = map[string]int32{
	"kCIM_MSG_FEATURE_DEFAULT":  0,
	"kCIM_MSG_FEATURE_ROAM_MSG": 2,
}

func (x CIMMsgFeature) String() string {
	return proto.EnumName(CIMMsgFeature_name, int32(x))
}

func (CIMMsgFeature) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{8}
}

// Voip邀请类型
type CIMVoipInviteType int32

const (
	CIMVoipInviteType_kCIM_VOIP_INVITE_TYPE_UNKNOWN    CIMVoipInviteType = 0
	CIMVoipInviteType_kCIM_VOIP_INVITE_TYPE_VOICE_CALL CIMVoipInviteType = 1
	CIMVoipInviteType_kCIM_VOIP_INVITE_TYPE_VIDEO_CALL CIMVoipInviteType = 2
)

var CIMVoipInviteType_name = map[int32]string{
	0: "kCIM_VOIP_INVITE_TYPE_UNKNOWN",
	1: "kCIM_VOIP_INVITE_TYPE_VOICE_CALL",
	2: "kCIM_VOIP_INVITE_TYPE_VIDEO_CALL",
}

var CIMVoipInviteType_value = map[string]int32{
	"kCIM_VOIP_INVITE_TYPE_UNKNOWN":    0,
	"kCIM_VOIP_INVITE_TYPE_VOICE_CALL": 1,
	"kCIM_VOIP_INVITE_TYPE_VIDEO_CALL": 2,
}

func (x CIMVoipInviteType) String() string {
	return proto.EnumName(CIMVoipInviteType_name, int32(x))
}

func (CIMVoipInviteType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{9}
}

// Voip邀请状态
type CIMInviteRspCode int32

const (
	CIMInviteRspCode_kCIM_VOIP_INVITE_CODE_UNKNOWN CIMInviteRspCode = 0
	CIMInviteRspCode_kCIM_VOIP_INVITE_CODE_TRYING  CIMInviteRspCode = 100
	CIMInviteRspCode_kCIM_VOIP_INVITE_CODE_RINGING CIMInviteRspCode = 180
	CIMInviteRspCode_KCIM_VOIP_INVITE_CODE_OK      CIMInviteRspCode = 200
)

var CIMInviteRspCode_name = map[int32]string{
	0:   "kCIM_VOIP_INVITE_CODE_UNKNOWN",
	100: "kCIM_VOIP_INVITE_CODE_TRYING",
	180: "kCIM_VOIP_INVITE_CODE_RINGING",
	200: "KCIM_VOIP_INVITE_CODE_OK",
}

var CIMInviteRspCode_value = map[string]int32{
	"kCIM_VOIP_INVITE_CODE_UNKNOWN": 0,
	"kCIM_VOIP_INVITE_CODE_TRYING":  100,
	"kCIM_VOIP_INVITE_CODE_RINGING": 180,
	"KCIM_VOIP_INVITE_CODE_OK":      200,
}

func (x CIMInviteRspCode) String() string {
	return proto.EnumName(CIMInviteRspCode_name, int32(x))
}

func (CIMInviteRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{10}
}

// Voip挂断原因
type CIMVoipByeReason int32

const (
	CIMVoipByeReason_kCIM_VOIP_BYE_REASON_UNKNOWN              CIMVoipByeReason = 0
	CIMVoipByeReason_kCIM_VOIP_BYE_REASON_CANCEL               CIMVoipByeReason = 1
	CIMVoipByeReason_kCIM_VOIP_BYE_REASON_HANG_UP              CIMVoipByeReason = 2
	CIMVoipByeReason_kCIM_VOIP_BYE_REASON_BUSY                 CIMVoipByeReason = 3
	CIMVoipByeReason_kCIM_VOIP_BYE_REASON_ONLINE_CLIENT_REJECT CIMVoipByeReason = 4
	CIMVoipByeReason_kCIM_VOIP_BYE_REASON_OK                   CIMVoipByeReason = 5
)

var CIMVoipByeReason_name = map[int32]string{
	0: "kCIM_VOIP_BYE_REASON_UNKNOWN",
	1: "kCIM_VOIP_BYE_REASON_CANCEL",
	2: "kCIM_VOIP_BYE_REASON_HANG_UP",
	3: "kCIM_VOIP_BYE_REASON_BUSY",
	4: "kCIM_VOIP_BYE_REASON_ONLINE_CLIENT_REJECT",
	5: "kCIM_VOIP_BYE_REASON_OK",
}

var CIMVoipByeReason_value = map[string]int32{
	"kCIM_VOIP_BYE_REASON_UNKNOWN":              0,
	"kCIM_VOIP_BYE_REASON_CANCEL":               1,
	"kCIM_VOIP_BYE_REASON_HANG_UP":              2,
	"kCIM_VOIP_BYE_REASON_BUSY":                 3,
	"kCIM_VOIP_BYE_REASON_ONLINE_CLIENT_REJECT": 4,
	"kCIM_VOIP_BYE_REASON_OK":                   5,
}

func (x CIMVoipByeReason) String() string {
	return proto.EnumName(CIMVoipByeReason_name, int32(x))
}

func (CIMVoipByeReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{11}
}

// 消息错误码
type CIMResCode int32

const (
	CIMResCode_kCIM_RES_CODE_OK CIMResCode = 0
)

var CIMResCode_name = map[int32]string{
	0: "kCIM_RES_CODE_OK",
}

var CIMResCode_value = map[string]int32{
	"kCIM_RES_CODE_OK": 0,
}

func (x CIMResCode) String() string {
	return proto.EnumName(CIMResCode_name, int32(x))
}

func (CIMResCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{12}
}

// 用户信息
type CIMUserInfo struct {
	UserId   uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	//optional
	AttachInfo           string   `protobuf:"bytes,11,opt,name=attach_info,json=attachInfo,proto3" json:"attach_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CIMUserInfo) Reset()         { *m = CIMUserInfo{} }
func (m *CIMUserInfo) String() string { return proto.CompactTextString(m) }
func (*CIMUserInfo) ProtoMessage()    {}
func (*CIMUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{0}
}

func (m *CIMUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CIMUserInfo.Unmarshal(m, b)
}
func (m *CIMUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CIMUserInfo.Marshal(b, m, deterministic)
}
func (m *CIMUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CIMUserInfo.Merge(m, src)
}
func (m *CIMUserInfo) XXX_Size() int {
	return xxx_messageInfo_CIMUserInfo.Size(m)
}
func (m *CIMUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CIMUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CIMUserInfo proto.InternalMessageInfo

func (m *CIMUserInfo) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CIMUserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CIMUserInfo) GetAttachInfo() string {
	if m != nil {
		return m.AttachInfo
	}
	return ""
}

// 会话信息
type CIMContactSessionInfo struct {
	SessionId     uint64               `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionType   CIMSessionType       `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=CIM.Def.CIMSessionType" json:"session_type,omitempty"`
	SessionStatus CIMSessionStatusType `protobuf:"varint,3,opt,name=session_status,json=sessionStatus,proto3,enum=CIM.Def.CIMSessionStatusType" json:"session_status,omitempty"`
	UnreadCnt     uint32               `protobuf:"varint,4,opt,name=unread_cnt,json=unreadCnt,proto3" json:"unread_cnt,omitempty"`
	UpdatedTime   uint32               `protobuf:"varint,5,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	MsgId         string               `protobuf:"bytes,6,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ServerMsgId   uint64               `protobuf:"varint,7,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	MsgTimeStamp  uint32               `protobuf:"varint,8,opt,name=msg_time_stamp,json=msgTimeStamp,proto3" json:"msg_time_stamp,omitempty"`
	MsgData       []byte               `protobuf:"bytes,9,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	MsgType       CIMMsgType           `protobuf:"varint,10,opt,name=msg_type,json=msgType,proto3,enum=CIM.Def.CIMMsgType" json:"msg_type,omitempty"`
	MsgFromUserId uint64               `protobuf:"varint,11,opt,name=msg_from_user_id,json=msgFromUserId,proto3" json:"msg_from_user_id,omitempty"`
	MsgStatus     CIMMsgStatus         `protobuf:"varint,12,opt,name=msg_status,json=msgStatus,proto3,enum=CIM.Def.CIMMsgStatus" json:"msg_status,omitempty"`
	//optional
	MsgAttach string `protobuf:"bytes,13,opt,name=msg_attach,json=msgAttach,proto3" json:"msg_attach,omitempty"`
	//optional
	ExtendData string `protobuf:"bytes,14,opt,name=extend_data,json=extendData,proto3" json:"extend_data,omitempty"`
	//optional
	IsRobotSession       bool     `protobuf:"varint,15,opt,name=is_robot_session,json=isRobotSession,proto3" json:"is_robot_session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CIMContactSessionInfo) Reset()         { *m = CIMContactSessionInfo{} }
func (m *CIMContactSessionInfo) String() string { return proto.CompactTextString(m) }
func (*CIMContactSessionInfo) ProtoMessage()    {}
func (*CIMContactSessionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{1}
}

func (m *CIMContactSessionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CIMContactSessionInfo.Unmarshal(m, b)
}
func (m *CIMContactSessionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CIMContactSessionInfo.Marshal(b, m, deterministic)
}
func (m *CIMContactSessionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CIMContactSessionInfo.Merge(m, src)
}
func (m *CIMContactSessionInfo) XXX_Size() int {
	return xxx_messageInfo_CIMContactSessionInfo.Size(m)
}
func (m *CIMContactSessionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CIMContactSessionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CIMContactSessionInfo proto.InternalMessageInfo

func (m *CIMContactSessionInfo) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CIMContactSessionInfo) GetSessionType() CIMSessionType {
	if m != nil {
		return m.SessionType
	}
	return CIMSessionType_kCIM_SESSION_TYPE_Invalid
}

func (m *CIMContactSessionInfo) GetSessionStatus() CIMSessionStatusType {
	if m != nil {
		return m.SessionStatus
	}
	return CIMSessionStatusType_kCIM_SESSION_STATUS_OK
}

func (m *CIMContactSessionInfo) GetUnreadCnt() uint32 {
	if m != nil {
		return m.UnreadCnt
	}
	return 0
}

func (m *CIMContactSessionInfo) GetUpdatedTime() uint32 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

func (m *CIMContactSessionInfo) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *CIMContactSessionInfo) GetServerMsgId() uint64 {
	if m != nil {
		return m.ServerMsgId
	}
	return 0
}

func (m *CIMContactSessionInfo) GetMsgTimeStamp() uint32 {
	if m != nil {
		return m.MsgTimeStamp
	}
	return 0
}

func (m *CIMContactSessionInfo) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *CIMContactSessionInfo) GetMsgType() CIMMsgType {
	if m != nil {
		return m.MsgType
	}
	return CIMMsgType_kCIM_MSG_TYPE_UNKNOWN
}

func (m *CIMContactSessionInfo) GetMsgFromUserId() uint64 {
	if m != nil {
		return m.MsgFromUserId
	}
	return 0
}

func (m *CIMContactSessionInfo) GetMsgStatus() CIMMsgStatus {
	if m != nil {
		return m.MsgStatus
	}
	return CIMMsgStatus_kCIM_MSG_STATUS_NONE
}

func (m *CIMContactSessionInfo) GetMsgAttach() string {
	if m != nil {
		return m.MsgAttach
	}
	return ""
}

func (m *CIMContactSessionInfo) GetExtendData() string {
	if m != nil {
		return m.ExtendData
	}
	return ""
}

func (m *CIMContactSessionInfo) GetIsRobotSession() bool {
	if m != nil {
		return m.IsRobotSession
	}
	return false
}

// 消息信息
type CIMMsgInfo struct {
	ClientMsgId string         `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ServerMsgId uint64         `protobuf:"varint,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	MsgResCode  CIMResCode     `protobuf:"varint,3,opt,name=msg_res_code,json=msgResCode,proto3,enum=CIM.Def.CIMResCode" json:"msg_res_code,omitempty"`
	MsgFeature  CIMMsgFeature  `protobuf:"varint,4,opt,name=msg_feature,json=msgFeature,proto3,enum=CIM.Def.CIMMsgFeature" json:"msg_feature,omitempty"`
	SessionType CIMSessionType `protobuf:"varint,5,opt,name=session_type,json=sessionType,proto3,enum=CIM.Def.CIMSessionType" json:"session_type,omitempty"`
	FromUserId  uint64         `protobuf:"varint,6,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToSessionId uint64         `protobuf:"varint,7,opt,name=to_session_id,json=toSessionId,proto3" json:"to_session_id,omitempty"`
	CreateTime  uint32         `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MsgType     CIMMsgType     `protobuf:"varint,9,opt,name=msg_type,json=msgType,proto3,enum=CIM.Def.CIMMsgType" json:"msg_type,omitempty"`
	MsgStatus   CIMMsgStatus   `protobuf:"varint,10,opt,name=msg_status,json=msgStatus,proto3,enum=CIM.Def.CIMMsgStatus" json:"msg_status,omitempty"`
	MsgData     []byte         `protobuf:"bytes,11,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	//optional
	Attach               string        `protobuf:"bytes,12,opt,name=attach,proto3" json:"attach,omitempty"`
	SenderClientType     CIMClientType `protobuf:"varint,13,opt,name=sender_client_type,json=senderClientType,proto3,enum=CIM.Def.CIMClientType" json:"sender_client_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CIMMsgInfo) Reset()         { *m = CIMMsgInfo{} }
func (m *CIMMsgInfo) String() string { return proto.CompactTextString(m) }
func (*CIMMsgInfo) ProtoMessage()    {}
func (*CIMMsgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{2}
}

func (m *CIMMsgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CIMMsgInfo.Unmarshal(m, b)
}
func (m *CIMMsgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CIMMsgInfo.Marshal(b, m, deterministic)
}
func (m *CIMMsgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CIMMsgInfo.Merge(m, src)
}
func (m *CIMMsgInfo) XXX_Size() int {
	return xxx_messageInfo_CIMMsgInfo.Size(m)
}
func (m *CIMMsgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CIMMsgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CIMMsgInfo proto.InternalMessageInfo

func (m *CIMMsgInfo) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *CIMMsgInfo) GetServerMsgId() uint64 {
	if m != nil {
		return m.ServerMsgId
	}
	return 0
}

func (m *CIMMsgInfo) GetMsgResCode() CIMResCode {
	if m != nil {
		return m.MsgResCode
	}
	return CIMResCode_kCIM_RES_CODE_OK
}

func (m *CIMMsgInfo) GetMsgFeature() CIMMsgFeature {
	if m != nil {
		return m.MsgFeature
	}
	return CIMMsgFeature_kCIM_MSG_FEATURE_DEFAULT
}

func (m *CIMMsgInfo) GetSessionType() CIMSessionType {
	if m != nil {
		return m.SessionType
	}
	return CIMSessionType_kCIM_SESSION_TYPE_Invalid
}

func (m *CIMMsgInfo) GetFromUserId() uint64 {
	if m != nil {
		return m.FromUserId
	}
	return 0
}

func (m *CIMMsgInfo) GetToSessionId() uint64 {
	if m != nil {
		return m.ToSessionId
	}
	return 0
}

func (m *CIMMsgInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *CIMMsgInfo) GetMsgType() CIMMsgType {
	if m != nil {
		return m.MsgType
	}
	return CIMMsgType_kCIM_MSG_TYPE_UNKNOWN
}

func (m *CIMMsgInfo) GetMsgStatus() CIMMsgStatus {
	if m != nil {
		return m.MsgStatus
	}
	return CIMMsgStatus_kCIM_MSG_STATUS_NONE
}

func (m *CIMMsgInfo) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *CIMMsgInfo) GetAttach() string {
	if m != nil {
		return m.Attach
	}
	return ""
}

func (m *CIMMsgInfo) GetSenderClientType() CIMClientType {
	if m != nil {
		return m.SenderClientType
	}
	return CIMClientType_kCIM_CLIENT_TYPE_DEFAULT
}

// VOIP频道信息
type CIMChannelInfo struct {
	ChannelName          string   `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChannelToken         string   `protobuf:"bytes,2,opt,name=channel_token,json=channelToken,proto3" json:"channel_token,omitempty"`
	CreatorId            uint64   `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CIMChannelInfo) Reset()         { *m = CIMChannelInfo{} }
func (m *CIMChannelInfo) String() string { return proto.CompactTextString(m) }
func (*CIMChannelInfo) ProtoMessage()    {}
func (*CIMChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f2b4dd9a8c1a4e, []int{3}
}

func (m *CIMChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CIMChannelInfo.Unmarshal(m, b)
}
func (m *CIMChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CIMChannelInfo.Marshal(b, m, deterministic)
}
func (m *CIMChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CIMChannelInfo.Merge(m, src)
}
func (m *CIMChannelInfo) XXX_Size() int {
	return xxx_messageInfo_CIMChannelInfo.Size(m)
}
func (m *CIMChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CIMChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CIMChannelInfo proto.InternalMessageInfo

func (m *CIMChannelInfo) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *CIMChannelInfo) GetChannelToken() string {
	if m != nil {
		return m.ChannelToken
	}
	return ""
}

func (m *CIMChannelInfo) GetCreatorId() uint64 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func init() {
	proto.RegisterEnum("CIM.Def.CIMCmdID", CIMCmdID_name, CIMCmdID_value)
	proto.RegisterEnum("CIM.Def.CIMIntenralCmdID", CIMIntenralCmdID_name, CIMIntenralCmdID_value)
	proto.RegisterEnum("CIM.Def.CIMErrorCode", CIMErrorCode_name, CIMErrorCode_value)
	proto.RegisterEnum("CIM.Def.CIMClientType", CIMClientType_name, CIMClientType_value)
	proto.RegisterEnum("CIM.Def.CIMSessionType", CIMSessionType_name, CIMSessionType_value)
	proto.RegisterEnum("CIM.Def.CIMMsgType", CIMMsgType_name, CIMMsgType_value)
	proto.RegisterEnum("CIM.Def.CIMMsgStatus", CIMMsgStatus_name, CIMMsgStatus_value)
	proto.RegisterEnum("CIM.Def.CIMSessionStatusType", CIMSessionStatusType_name, CIMSessionStatusType_value)
	proto.RegisterEnum("CIM.Def.CIMMsgFeature", CIMMsgFeature_name, CIMMsgFeature_value)
	proto.RegisterEnum("CIM.Def.CIMVoipInviteType", CIMVoipInviteType_name, CIMVoipInviteType_value)
	proto.RegisterEnum("CIM.Def.CIMInviteRspCode", CIMInviteRspCode_name, CIMInviteRspCode_value)
	proto.RegisterEnum("CIM.Def.CIMVoipByeReason", CIMVoipByeReason_name, CIMVoipByeReason_value)
	proto.RegisterEnum("CIM.Def.CIMResCode", CIMResCode_name, CIMResCode_value)
	proto.RegisterType((*CIMUserInfo)(nil), "CIM.Def.CIMUserInfo")
	proto.RegisterType((*CIMContactSessionInfo)(nil), "CIM.Def.CIMContactSessionInfo")
	proto.RegisterType((*CIMMsgInfo)(nil), "CIM.Def.CIMMsgInfo")
	proto.RegisterType((*CIMChannelInfo)(nil), "CIM.Def.CIMChannelInfo")
}

func init() { proto.RegisterFile("CIM.Def.proto", fileDescriptor_59f2b4dd9a8c1a4e) }

var fileDescriptor_59f2b4dd9a8c1a4e = []byte{
	// 1732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcb, 0x72, 0xdb, 0xc8,
	0x15, 0x15, 0x28, 0x8a, 0x22, 0x9b, 0x8f, 0xf4, 0xf4, 0xd8, 0x12, 0xfd, 0x90, 0x4d, 0x73, 0xa6,
	0x32, 0x0a, 0xab, 0x46, 0x8b, 0x49, 0x52, 0xa9, 0xca, 0x0e, 0x04, 0x9a, 0x74, 0x47, 0x20, 0xc0,
	0x00, 0x4d, 0xcd, 0x28, 0x1b, 0x14, 0x4c, 0x34, 0x65, 0xc6, 0x22, 0xa0, 0x22, 0x20, 0x27, 0x5e,
	0xa5, 0xc6, 0x63, 0xcf, 0x64, 0x97, 0x7d, 0x96, 0xf9, 0x86, 0x7c, 0x41, 0x16, 0x29, 0x27, 0x95,
	0xaf, 0xc8, 0x0f, 0xe4, 0x17, 0x52, 0xdd, 0x0d, 0x80, 0x80, 0x08, 0xc5, 0xca, 0x8e, 0xb8, 0xe7,
	0xf4, 0xed, 0xfb, 0x38, 0xf7, 0x02, 0x12, 0x68, 0x6b, 0x64, 0x72, 0xa2, 0xb3, 0xc5, 0xc9, 0xd5,
	0x3a, 0x8c, 0x43, 0xb4, 0x9f, 0x3c, 0xf6, 0x7d, 0xd0, 0xd4, 0xc8, 0x64, 0x16, 0xb1, 0x35, 0x09,
	0x16, 0x21, 0x3a, 0x04, 0xfb, 0xd7, 0x11, 0x5b, 0xbb, 0x4b, 0xbf, 0xab, 0xf4, 0x94, 0xe3, 0xaa,
	0x5d, 0xe3, 0x8f, 0xc4, 0x47, 0x8f, 0x40, 0x23, 0x58, 0xce, 0x5f, 0xb9, 0x81, 0xb7, 0x62, 0xdd,
	0x4a, 0x4f, 0x39, 0x6e, 0xd8, 0x75, 0x6e, 0x30, 0xbd, 0x15, 0x43, 0x4f, 0x41, 0xd3, 0x8b, 0x63,
	0x6f, 0xfe, 0xd2, 0x5d, 0x06, 0x8b, 0xb0, 0xdb, 0x14, 0x30, 0x90, 0x26, 0xee, 0xb6, 0xff, 0x9f,
	0x2a, 0xb8, 0xaf, 0x91, 0x89, 0x16, 0x06, 0xb1, 0x37, 0x8f, 0x1d, 0x16, 0x45, 0xcb, 0x30, 0x10,
	0x17, 0x1e, 0x01, 0x10, 0xc9, 0xc7, 0xcd, 0x9d, 0x8d, 0xc4, 0x42, 0x7c, 0xf4, 0x4b, 0xd0, 0x4a,
	0xe1, 0xf8, 0xcd, 0x95, 0xbc, 0xb9, 0xf3, 0xd5, 0xe1, 0x49, 0x9a, 0x8d, 0x46, 0x26, 0x89, 0x37,
	0xfa, 0xe6, 0x8a, 0xd9, 0xcd, 0x68, 0xf3, 0x80, 0x74, 0xd0, 0x49, 0xcf, 0x46, 0xb1, 0x17, 0x5f,
	0x47, 0xdd, 0x5d, 0x71, 0xfa, 0xa8, 0xe4, 0xb4, 0x23, 0x08, 0xc2, 0x47, 0x3b, 0xca, 0x9b, 0x78,
	0x80, 0xd7, 0xc1, 0x9a, 0x79, 0xbe, 0x3b, 0x0f, 0xe2, 0x6e, 0xb5, 0xa7, 0x1c, 0xb7, 0xed, 0x86,
	0xb4, 0x68, 0x41, 0x8c, 0x9e, 0x81, 0xd6, 0xf5, 0x95, 0xef, 0xc5, 0xcc, 0x77, 0xe3, 0xe5, 0x8a,
	0x75, 0xf7, 0x04, 0xa1, 0x99, 0xd8, 0xe8, 0x72, 0xc5, 0xd0, 0x7d, 0x50, 0x5b, 0x45, 0x17, 0x3c,
	0xbd, 0x9a, 0x28, 0xcc, 0xde, 0x2a, 0xba, 0x20, 0x3e, 0xea, 0x83, 0x76, 0xc4, 0xd6, 0xaf, 0xd9,
	0xda, 0x4d, 0xd0, 0x7d, 0x91, 0x7c, 0x53, 0x1a, 0x27, 0x82, 0xf3, 0x39, 0xe8, 0x70, 0x90, 0x7b,
	0xe6, 0x39, 0xac, 0xae, 0xba, 0x75, 0xe1, 0xbf, 0xb5, 0x8a, 0x2e, 0xb8, 0x6f, 0x87, 0xdb, 0xd0,
	0x03, 0x50, 0xe7, 0x2c, 0xdf, 0x8b, 0xbd, 0x6e, 0xa3, 0xa7, 0x1c, 0xb7, 0xec, 0xfd, 0x55, 0x74,
	0xa1, 0x7b, 0xb1, 0x87, 0x4e, 0x24, 0x24, 0x6a, 0x07, 0x44, 0xf6, 0x9f, 0xe6, 0xb3, 0x9f, 0x44,
	0x17, 0x22, 0x67, 0xce, 0x17, 0x35, 0xfb, 0x02, 0x40, 0xce, 0x5f, 0xac, 0xc3, 0x95, 0x9b, 0x0a,
	0xa1, 0x29, 0xe2, 0x6a, 0xaf, 0xa2, 0x8b, 0xd1, 0x3a, 0x5c, 0xcd, 0xa4, 0x1e, 0x7e, 0x06, 0x00,
	0x27, 0x26, 0x85, 0x6d, 0x09, 0xd7, 0xf7, 0x6f, 0xb8, 0x96, 0x15, 0xb4, 0x1b, 0xab, 0xf4, 0x27,
	0x2f, 0x26, 0x3f, 0x25, 0x95, 0xd1, 0x6d, 0x8b, 0x72, 0x70, 0x58, 0x15, 0x06, 0xae, 0x23, 0xf6,
	0xfb, 0x98, 0x05, 0xbe, 0xcc, 0xa5, 0x23, 0x75, 0x24, 0x4d, 0x22, 0x9d, 0x63, 0x00, 0x97, 0x91,
	0xbb, 0x0e, 0x5f, 0x84, 0xb1, 0x9b, 0xb4, 0xa9, 0xfb, 0xa3, 0x9e, 0x72, 0x5c, 0xb7, 0x3b, 0xcb,
	0xc8, 0xe6, 0xe6, 0xa4, 0x9f, 0xfd, 0xbf, 0x57, 0x01, 0x90, 0x51, 0x08, 0x99, 0xf5, 0x41, 0x7b,
	0x7e, 0xb9, 0x64, 0x41, 0x9c, 0x16, 0x5b, 0x11, 0xbe, 0x9b, 0xd2, 0x38, 0x29, 0x6f, 0x48, 0x65,
	0xbb, 0x21, 0x3f, 0x07, 0xbc, 0xf4, 0xee, 0x9a, 0x45, 0xee, 0x3c, 0xf4, 0x59, 0xa2, 0xa8, 0x42,
	0x4d, 0x6d, 0x16, 0x69, 0xa1, 0xcf, 0x6c, 0x9e, 0x69, 0xf2, 0x1b, 0xfd, 0x02, 0x34, 0x45, 0x59,
	0x99, 0x17, 0x5f, 0xaf, 0x99, 0x50, 0x51, 0xe7, 0xab, 0x83, 0x1b, 0xe5, 0x1a, 0x49, 0x54, 0x1c,
	0x4c, 0x7e, 0x6f, 0xe9, 0x7f, 0xef, 0xff, 0xd0, 0x7f, 0x0f, 0xb4, 0x0a, 0x7d, 0xac, 0x89, 0x74,
	0xc0, 0x62, 0xd3, 0xc4, 0x3e, 0x68, 0xc7, 0xa1, 0x9b, 0x9b, 0xbf, 0x44, 0x82, 0x71, 0xe8, 0x64,
	0x13, 0xf8, 0x14, 0x34, 0xe7, 0x6b, 0xe6, 0xc5, 0x4c, 0xea, 0x5b, 0xea, 0x0f, 0x48, 0x93, 0x90,
	0x77, 0x5e, 0x62, 0x8d, 0x3b, 0x48, 0xac, 0xa8, 0x1c, 0x70, 0x47, 0xe5, 0xe4, 0x35, 0xde, 0x2c,
	0x6a, 0xfc, 0x00, 0xd4, 0x12, 0x41, 0xb5, 0x44, 0x53, 0x93, 0x27, 0xa4, 0x03, 0x14, 0xb1, 0xc0,
	0x67, 0x6b, 0x37, 0x69, 0xbd, 0x08, 0xb1, 0xbd, 0x5d, 0x7b, 0x4d, 0xc0, 0x22, 0x4a, 0x28, 0x4f,
	0x6c, 0x2c, 0xfd, 0xdf, 0x81, 0x0e, 0xa7, 0xbc, 0xf4, 0x82, 0x80, 0x5d, 0x0a, 0x2d, 0x3d, 0x03,
	0xad, 0xb9, 0x7c, 0x94, 0xdb, 0x30, 0x95, 0x92, 0xb4, 0x89, 0x85, 0xf8, 0x19, 0x68, 0xa7, 0x94,
	0x38, 0x7c, 0xc5, 0x82, 0x64, 0x63, 0xa6, 0xe7, 0x28, 0xb7, 0xf1, 0x61, 0x10, 0x65, 0x0c, 0x45,
	0x77, 0x76, 0xe5, 0xea, 0x4b, 0x2c, 0xc4, 0x1f, 0xfc, 0xab, 0x06, 0xea, 0xfc, 0xe6, 0x95, 0x4f,
	0x74, 0x74, 0x0f, 0xc0, 0x57, 0x1a, 0x99, 0xb8, 0x1a, 0xd1, 0xdd, 0x99, 0x79, 0x6a, 0x5a, 0x5f,
	0x9b, 0x70, 0x07, 0xf5, 0xc1, 0x51, 0x66, 0x35, 0xac, 0x31, 0x31, 0x5d, 0x75, 0x46, 0x9f, 0xbb,
	0xd4, 0x3a, 0xc5, 0xa6, 0x6b, 0xe3, 0x5f, 0xc3, 0x6f, 0x2b, 0x1f, 0xe1, 0x38, 0x53, 0xf8, 0xb6,
	0x82, 0x3e, 0x03, 0x4f, 0xca, 0x38, 0x86, 0x35, 0xb6, 0x66, 0x54, 0x38, 0xfa, 0xee, 0xa3, 0x24,
	0x67, 0x0a, 0xdf, 0x55, 0xd0, 0x11, 0xe8, 0xde, 0x20, 0x3d, 0xc7, 0xaa, 0x4d, 0x87, 0x58, 0xa5,
	0xf0, 0x7d, 0x05, 0x7d, 0x09, 0x8e, 0x37, 0x30, 0x71, 0xb8, 0x6f, 0x0d, 0x9b, 0xd4, 0xd5, 0x2c,
	0x93, 0xaa, 0x1a, 0x75, 0x1d, 0xec, 0x38, 0xc4, 0x4a, 0x62, 0xaf, 0xde, 0x9d, 0xce, 0xd3, 0xa8,
	0xa2, 0x87, 0xe0, 0x7e, 0x91, 0x3e, 0x71, 0xc6, 0xc2, 0xd5, 0xfb, 0xdb, 0x30, 0x67, 0x0a, 0xbf,
	0xaf, 0xa2, 0x03, 0xf0, 0x49, 0x86, 0x71, 0xb3, 0xae, 0x52, 0x15, 0x7e, 0x5b, 0x2b, 0x9c, 0x49,
	0xed, 0xae, 0xaa, 0x9d, 0xc2, 0xb7, 0xdb, 0x98, 0x8d, 0x55, 0x5d, 0x60, 0xdf, 0xd5, 0x0a, 0x45,
	0xc8, 0x30, 0xd3, 0xa2, 0x64, 0x74, 0x0e, 0xdf, 0xd5, 0xd0, 0x17, 0xa0, 0x5f, 0x80, 0xc7, 0x98,
	0xba, 0x86, 0x4a, 0x71, 0x12, 0x14, 0xd1, 0x65, 0xcc, 0x77, 0x22, 0xf2, 0x04, 0x6a, 0x85, 0xd6,
	0xa4, 0xc4, 0xe1, 0x79, 0xde, 0xdb, 0x0f, 0x1f, 0x25, 0x39, 0x53, 0xf8, 0xc7, 0x62, 0xe8, 0x67,
	0x16, 0x99, 0xba, 0xc4, 0x3c, 0x23, 0x14, 0xcb, 0x86, 0xd4, 0xd1, 0x53, 0xf0, 0xf0, 0x16, 0x78,
	0x6a, 0x9c, 0xc3, 0xb7, 0xf5, 0xc2, 0x25, 0x5b, 0x04, 0x59, 0x9f, 0x3a, 0x7a, 0x0c, 0x0e, 0x8b,
	0xa4, 0x8d, 0x46, 0xde, 0xd5, 0x0b, 0x95, 0x15, 0xe8, 0xf0, 0x5c, 0xde, 0xff, 0xfe, 0x36, 0x8c,
	0x17, 0xa1, 0xbe, 0x1d, 0x3a, 0xc7, 0x92, 0xaa, 0xff, 0x50, 0x1f, 0x2c, 0x00, 0xd4, 0xc8, 0x84,
	0x04, 0x31, 0x0b, 0xd6, 0xde, 0x65, 0x71, 0xaa, 0x9c, 0xc2, 0x54, 0xa5, 0x8e, 0xb8, 0x55, 0x1f,
	0xba, 0x67, 0xaa, 0x41, 0x74, 0x35, 0xad, 0x41, 0xe7, 0x76, 0x98, 0x8b, 0xb0, 0x33, 0xf8, 0x4b,
	0x05, 0xb4, 0x34, 0x32, 0xc1, 0xeb, 0x75, 0xb8, 0x16, 0xbb, 0x3f, 0xbd, 0x04, 0xdb, 0xb6, 0xeb,
	0xcc, 0x34, 0xcd, 0x71, 0x30, 0xdc, 0x41, 0x8f, 0x92, 0x1a, 0x70, 0x2b, 0x31, 0x29, 0xb6, 0x4d,
	0xd5, 0xe0, 0x0f, 0x96, 0x0d, 0x15, 0xf4, 0x63, 0xf0, 0x2c, 0x03, 0xe5, 0x14, 0xe5, 0x2f, 0x1a,
	0xa9, 0xc4, 0xc0, 0x3a, 0xfc, 0xa0, 0x64, 0xd5, 0xde, 0xf0, 0xce, 0xb0, 0x2d, 0x26, 0x82, 0x5a,
	0x96, 0x6b, 0x19, 0x3a, 0xfc, 0x47, 0x99, 0x33, 0x62, 0x0a, 0x5f, 0xee, 0xcc, 0xc1, 0xb6, 0x5c,
	0x04, 0xf0, 0x9f, 0x4a, 0xb6, 0x28, 0x44, 0x10, 0x12, 0x53, 0x0d, 0x2e, 0xdd, 0x73, 0x17, 0x7f,
	0x43, 0x1c, 0x0a, 0xdf, 0xed, 0xe7, 0x7d, 0xa5, 0x9c, 0xd4, 0xd9, 0x54, 0xb5, 0xd5, 0x09, 0xa6,
	0xd8, 0x86, 0xef, 0xf7, 0xd1, 0x13, 0xf0, 0xe0, 0x26, 0xcf, 0xb4, 0x68, 0xe2, 0xe7, 0xfb, 0xfd,
	0xc1, 0x1f, 0xc4, 0xf7, 0xe8, 0x66, 0xcb, 0xa2, 0xc7, 0x69, 0xf3, 0x0c, 0xc2, 0x07, 0x9c, 0x9e,
	0x4f, 0xb1, 0xab, 0xe3, 0x91, 0x3a, 0x33, 0x28, 0xdc, 0x29, 0x45, 0x55, 0x53, 0xb7, 0x2d, 0xa2,
	0x43, 0x05, 0x75, 0xc1, 0xbd, 0x2d, 0x94, 0x58, 0x0e, 0xac, 0x94, 0x22, 0x5f, 0xe3, 0x21, 0xdc,
	0x1d, 0xfc, 0x56, 0x6c, 0xf5, 0xdc, 0xab, 0x13, 0x1d, 0x25, 0x21, 0xa7, 0x3b, 0x45, 0xba, 0x09,
	0x5e, 0x7b, 0x97, 0x4b, 0x3f, 0x17, 0x42, 0x01, 0x76, 0x88, 0x39, 0x36, 0x30, 0x54, 0xb2, 0x6e,
	0x16, 0xd0, 0xb1, 0x6d, 0xcd, 0xa6, 0xb0, 0x32, 0xf8, 0x53, 0x25, 0xfd, 0x14, 0x11, 0x17, 0x3d,
	0x48, 0x34, 0xcc, 0x07, 0x4f, 0xf0, 0x36, 0xca, 0x3b, 0x00, 0xa8, 0x08, 0x51, 0xfc, 0x0d, 0x85,
	0xca, 0xb6, 0x7d, 0x44, 0x0c, 0x0c, 0x2b, 0xe8, 0x10, 0x7c, 0x5a, 0xb4, 0x93, 0x89, 0x3a, 0xc6,
	0x70, 0x77, 0x1b, 0x50, 0x67, 0x3a, 0xb1, 0x60, 0x75, 0x1b, 0x38, 0x23, 0x3a, 0xb6, 0xe0, 0x1e,
	0x7a, 0x08, 0x0e, 0x8a, 0x80, 0x61, 0x69, 0x2a, 0x25, 0x96, 0x09, 0x6b, 0xdb, 0x87, 0x6c, 0x6b,
	0x68, 0x51, 0xb8, 0x5f, 0x12, 0x2f, 0x99, 0x3a, 0xb0, 0x8e, 0x9e, 0x24, 0x6b, 0x22, 0xb3, 0x8b,
	0x31, 0x54, 0x13, 0x87, 0x8d, 0xc1, 0xdf, 0xe4, 0x8c, 0x64, 0x2f, 0xfa, 0xac, 0x51, 0xfc, 0x80,
	0x43, 0x55, 0x3a, 0x73, 0x5c, 0xd3, 0x32, 0xf9, 0x9c, 0xe4, 0xe3, 0x4a, 0x90, 0x99, 0xc9, 0x55,
	0x99, 0x6b, 0x7c, 0x0e, 0x13, 0x48, 0x25, 0xeb, 0x47, 0x0e, 0xd1, 0xb1, 0x81, 0x29, 0xd6, 0xe1,
	0x6e, 0x19, 0xe8, 0x60, 0x53, 0x27, 0xe6, 0x18, 0x56, 0xcb, 0x7c, 0x3a, 0xd8, 0xa4, 0x70, 0xaf,
	0xec, 0x18, 0x7f, 0x1d, 0x91, 0x29, 0x85, 0xb5, 0x42, 0x53, 0xd3, 0x0b, 0x6d, 0x75, 0xc4, 0x8b,
	0x94, 0x0a, 0x2b, 0xef, 0x91, 0x05, 0xbe, 0xe6, 0xcd, 0xd9, 0x25, 0xac, 0x97, 0xbb, 0x1d, 0xcd,
	0x1c, 0xac, 0xc3, 0x46, 0x59, 0xf6, 0xc9, 0xf4, 0x83, 0x81, 0x0d, 0xee, 0x95, 0xfd, 0xfd, 0x92,
	0x9d, 0x49, 0xb5, 0x98, 0x9c, 0xb3, 0x4e, 0xe1, 0x4e, 0xd6, 0x98, 0x1b, 0x98, 0xac, 0x0d, 0x54,
	0x06, 0x86, 0x98, 0xcb, 0xcd, 0xb7, 0x68, 0x26, 0x7b, 0x1e, 0xc0, 0x08, 0xab, 0x74, 0x66, 0xe7,
	0xe7, 0x32, 0x9f, 0x5a, 0x8a, 0xda, 0x96, 0x2a, 0x0c, 0xb0, 0x32, 0x78, 0xab, 0x80, 0x4f, 0x34,
	0x32, 0x39, 0x0b, 0x97, 0x57, 0x24, 0x78, 0xbd, 0x8c, 0x99, 0x88, 0xef, 0x59, 0xb2, 0x67, 0xf2,
	0xaf, 0x87, 0x1b, 0x73, 0xf0, 0x39, 0xe8, 0x95, 0x53, 0xce, 0x2c, 0xa2, 0x61, 0x57, 0x53, 0x0d,
	0x03, 0x2a, 0xff, 0x83, 0xc5, 0x35, 0x2d, 0x59, 0x95, 0xc1, 0x9f, 0x95, 0x64, 0xf1, 0xf3, 0x00,
	0xec, 0xe8, 0x4a, 0xec, 0xe4, 0xb2, 0x18, 0x34, 0x4b, 0xcf, 0xc7, 0xd0, 0x03, 0x8f, 0xcb, 0x29,
	0xd4, 0x3e, 0xe7, 0x52, 0xf1, 0xb3, 0x85, 0xb9, 0xc5, 0xb0, 0x89, 0x39, 0xe6, 0x94, 0xbf, 0x2a,
	0xfc, 0x65, 0x71, 0x5a, 0xca, 0xb1, 0x4e, 0xe1, 0x07, 0x65, 0xf0, 0x6f, 0x19, 0x1c, 0xaf, 0xd0,
	0xf0, 0x0d, 0xb3, 0x99, 0x17, 0x85, 0x41, 0xf1, 0x66, 0xf9, 0xf2, 0x53, 0x1d, 0xcb, 0xcc, 0xc5,
	0xf6, 0x14, 0x3c, 0x2a, 0x65, 0x68, 0xaa, 0xa9, 0x61, 0x5e, 0x9a, 0xdb, 0x5c, 0x3c, 0x57, 0xcd,
	0xb1, 0xcb, 0x97, 0x52, 0xd6, 0xba, 0x9b, 0x8c, 0xe1, 0xcc, 0x39, 0x87, 0xbb, 0xe8, 0x4b, 0xf0,
	0x93, 0x52, 0xd8, 0x32, 0x0d, 0x62, 0xe2, 0x74, 0xa1, 0xda, 0xf8, 0x57, 0x58, 0xa3, 0xb0, 0x9a,
	0x89, 0x78, 0x8b, 0x7e, 0x0a, 0xf7, 0x06, 0x7d, 0xb1, 0xfe, 0xd2, 0x3f, 0x85, 0xd2, 0xd7, 0xa1,
	0x8d, 0x9d, 0xac, 0x12, 0x3b, 0xc3, 0x1e, 0x38, 0x9c, 0x87, 0xab, 0x93, 0x79, 0xb8, 0x58, 0x30,
	0x36, 0x7f, 0xe9, 0xc5, 0xf2, 0xff, 0x14, 0x2f, 0xae, 0x17, 0xcf, 0x77, 0x7f, 0xb3, 0x3b, 0x5f,
	0xae, 0x5e, 0xd4, 0x84, 0xe1, 0xa7, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x7b, 0x3e, 0x50,
	0xc9, 0x10, 0x00, 0x00,
}
