// Code generated by ent, DO NOT EDIT.

package ent

import (
	"CoffeeChat/internal/chat/data/ent/messagerecv"
	"CoffeeChat/internal/chat/data/ent/messagesend"
	"CoffeeChat/internal/chat/data/ent/session"
	"CoffeeChat/internal/chat/data/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messagerecvMixin := schema.MessageRecv{}.Mixin()
	messagerecvMixinFields1 := messagerecvMixin[1].Fields()
	_ = messagerecvMixinFields1
	messagerecvFields := schema.MessageRecv{}.Fields()
	_ = messagerecvFields
	// messagerecvDescCreatedAt is the schema descriptor for created_at field.
	messagerecvDescCreatedAt := messagerecvMixinFields1[0].Descriptor()
	// messagerecv.DefaultCreatedAt holds the default value on creation for the created_at field.
	messagerecv.DefaultCreatedAt = messagerecvDescCreatedAt.Default.(time.Time)
	// messagerecvDescUpdatedAt is the schema descriptor for updated_at field.
	messagerecvDescUpdatedAt := messagerecvMixinFields1[1].Descriptor()
	// messagerecv.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	messagerecv.DefaultUpdatedAt = messagerecvDescUpdatedAt.Default.(time.Time)
	// messagerecv.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	messagerecv.UpdateDefaultUpdatedAt = messagerecvDescUpdatedAt.UpdateDefault.(func() time.Time)
	messagesendMixin := schema.MessageSend{}.Mixin()
	messagesendMixinFields1 := messagesendMixin[1].Fields()
	_ = messagesendMixinFields1
	messagesendFields := schema.MessageSend{}.Fields()
	_ = messagesendFields
	// messagesendDescCreatedAt is the schema descriptor for created_at field.
	messagesendDescCreatedAt := messagesendMixinFields1[0].Descriptor()
	// messagesend.DefaultCreatedAt holds the default value on creation for the created_at field.
	messagesend.DefaultCreatedAt = messagesendDescCreatedAt.Default.(time.Time)
	// messagesendDescUpdatedAt is the schema descriptor for updated_at field.
	messagesendDescUpdatedAt := messagesendMixinFields1[1].Descriptor()
	// messagesend.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	messagesend.DefaultUpdatedAt = messagesendDescUpdatedAt.Default.(time.Time)
	// messagesend.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	messagesend.UpdateDefaultUpdatedAt = messagesendDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinFields0 := sessionMixin[0].Fields()
	_ = sessionMixinFields0
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreateTime is the schema descriptor for create_time field.
	sessionDescCreateTime := sessionMixinFields0[0].Descriptor()
	// session.DefaultCreateTime holds the default value on creation for the create_time field.
	session.DefaultCreateTime = sessionDescCreateTime.Default.(func() time.Time)
	// sessionDescUpdateTime is the schema descriptor for update_time field.
	sessionDescUpdateTime := sessionMixinFields0[1].Descriptor()
	// session.DefaultUpdateTime holds the default value on creation for the update_time field.
	session.DefaultUpdateTime = sessionDescUpdateTime.Default.(func() time.Time)
	// session.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	session.UpdateDefaultUpdateTime = sessionDescUpdateTime.UpdateDefault.(func() time.Time)
}
